#!/usr/bin/env ruby
require 'optparse'

options = {}
OptionParser.new do |opts|
  opts.banner = "Usage: christmas_tree [options]"

  opts.on("-nNAME", "--name=NAME", "name") do |name|
    options[:name] = name
  end

  opts.on("-mNAME", "--merry_to=NAME", "name") do |name|
    options[:name] = name
  end
end.parse!


begin
  require 'curses'
  require_relative '../lib/christmas_tree'
  ChristmasTree::Tree.new(options[:name]).draw
ensure
  Curses.close_screen
end
